services:
  - type: web
    name: dms-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - key: DB_HOST
        fromDatabase:
          name: dms-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: dms-postgres
          property: port
      - key: DB_NAME
        fromDatabase:
          name: dms-postgres
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: dms-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: dms-postgres
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

  - type: web
    name: dms-frontend
    runtime: docker
    rootDir: frontend
    dockerfilePath: ./Dockerfile
    plan: free

databases:
  - name: dms-postgres
    plan: free
    databaseName: delivery_db
    user: delivery_user